# GitHub Pages Configuration Variables

remote_theme: nikahmadz/prime-theme # The theme of your site

# title: Dark Switch # The title of your site
# description:
# favicon: favicon.ico
# manifest: manifest.json
# color_scheme: 'light dark'
# theme_color: '#202020'
